### PR TITLE
Chef 13 compatibility fixes

### PR DESCRIPTION
**Pull request by jcorme**
It doesn't appear that the package recipe does anything...in fact, converging it alone fails because there's no camo package in the repos. There shouldn't be any problems removing it...right?

### CODE REVIEW

**Comment by jcorme** [comment]
[Chef 13: camo](https://trello.com/c/B6vJCMqB/967-chef-13-camo)

**Comment by TravisWhitehead** [comment]
It appears we forked upstream for CentOS support. Do we still need this fork, or would it make sense to switch back to upstream (now that it does support CentOS)? I'm unsure of whether it supports Chef 13 or not.

**Comment by ramereth** [comment]
Yes I'd prefer to see if the newer upstream works like we need and then we don't need to worry about this fork.

@jcorme can you please look into that? You'd need to do that in proj-phpbb

**Comment by jcorme** [comment]
Closing this since we're using the upstream version in osuosl-cookbooks/proj-phpbb#252.

**Pull request closed without merging**
